# This is a generated file. Not intended for manual editing.
services:
  egressportal:
    build:
      context: "/home/ellison/source/repos/egress_program_front"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "egressportal:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "/home/ellison/.nuget/packages:/root/.nuget/packages"
    - "/home/ellison/source/repos/egress_program_front:/app:rw"
    - "/home/ellison/source/repos/egress_program_front:/src:rw"
    - "/home/ellison/.local/share/JetBrains/RiderRemoteDebugger/2024.1.2/Linux64:/opt/rider-debugger"
    - "/snap/rider/460/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/home/ellison/.cache/JetBrains/Rider2024.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2024_6_03_23_49_14:/var/opt/rider-debugger:rw"
    working_dir: "/app"
