# This is a generated file. Not intended for manual editing.
services:
  egressportal:
    build:
      context: "/Users/ellisonguimaraes/repos/EgressPortal"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-arm64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "egressportal:dev"
    ports:
    - "57001:57100"
    - "57201:57300"
    volumes:
    - "/Users/ellisonguimaraes/.aspnet/https:/root/.aspnet/https"
    - "/Users/ellisonguimaraes/.microsoft/usersecrets:/root/.microsoft/usersecrets"
    - "/Users/ellisonguimaraes/repos/EgressPortal:/app:rw"
    - "/Users/ellisonguimaraes/.local/share/JetBrains/RiderRemoteDebugger/2023.1/LinuxArm64:/riderDebugger"
    - "/Applications/Rider.app/Contents/bin:/riderLogsConf"
    - "/Users/ellisonguimaraes/Library/Logs/JetBrains/Rider2023.1/DebuggerWorker/JetBrains.Debugger.Worker.2023_10_18_03_48_04:/riderLogs:rw"
    working_dir: "/app"
