# This is a generated file. Not intended for manual editing.
services:
  egressportal:
    build:
      context: "C:\\Users\\ellis\\source\\repos\\egress_program_front"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\ellis\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\ellis\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "egressportal:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\ellis\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\ellis\\source\\repos\\egress_program_front:/app:rw"
    - "C:\\Users\\ellis\\source\\repos\\egress_program_front:/src:rw"
    - "C:\\Users\\ellis\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.2\\\
      Linux64:/riderDebugger"
    - "C:\\Users\\ellis\\AppData\\Local\\JetBrains\\Toolbox\\apps\\Rider\\ch-0\\232.9921.83/bin:/riderLogsConf"
    - "C:\\Users\\ellis\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_19_02_09_01:/riderLogs:rw"
    working_dir: "/app"
